### ISSUE TITLE
Define SEO settings for each page

### ISSUE THREAD

**Issue by kadosh1000** [nodee-apps/cms#4]
I would love the ability to define for each page its meta tags, including description, keywords, title and OG meta tags

**Comment by matusszabo** [comment]
Hi @kadosh1000, there are page attributes which are universal and can be used for anything related to page behaviour. Just define "seo_meta", "seo_keywords", "seo_description" attributes in layout template. Then use it in view mapping like: attributes.seo_meta. (Ensure you have meta, title, ... tags inside html, because if not, template compiler will skip it.)
