### ISSUE TITLE
Content Editor

### ISSUE THREAD

**Issue by ghost** [nodee-apps/cms#6]
Was just curious if you had any interest in improving the content editor. I like the option to switch between wysiwyg, html, and markdown, however the way it pops up does not allow the wysiwyg view to display properly. It might be nice to implement the editing directly into the page rather than a pop up. Also, the tool bar is kind of ugly. Otherwise, I really like this CMS and may look into contributing. That was my first item of interest, however. I'm wondering why this hasn't been starred several thousand times already.

**Comment by matusszabo** [comment]
Hi @barryanders, you are right, content editing may be nicer and "more inline". Current solution (via modals) is result of several compromises:
1. Hidden texts and editor groups - for example carousel, you can grab any JS carousel and paste it into page template, then apply editors e.g. image+text+link will be one editor group and it will be repeated for every carousel page - this way can copywriter edit rich texts inside carousel which are not visible (or are visible only few seconds)
2. html / markdown / wysiwyg - we are mainly using html and markdown editors, but some users requested wysiwyg, so we just added it as next tab
3. page scripts isolation - in many cases, there is some js framework used in content page to make it dynamic (single page apps), and binding admin editor methods to content page DOM elements may not be always 100% (e.g. repeated lists, animations, etc...) - yes there are techniques to avoid conflicts, but this solution give web developer freedom and he can be sure there will be almost zero conflicts

So main concept (or rule) is to avoid limitations of predefined cms widgets, let web developers use what they like and make it editable. We do not want to force developers write plugins just because they need some custom visual component. Maybe it is not ideal realisation of this idea, or maybe we are completely wrong - reason why I am writing so large comment, maybe you can help us make better decisions. But write plugin to add custom editors will be able in future, we are refactoring whole admin front-end.

And yes, there should be more stars, maybe you can help us with marketing :)
How did you found this project, google, forums, articles ?

Thank you.
